foo

diff --git a/patches/selftests-vm-only-run-128tbswitch-with-5-level-paging.patch b/patches/selftests-vm-only-run-128tbswitch-with-5-level-paging.patch
--- a/patches/selftests-vm-only-run-128tbswitch-with-5-level-paging.patch
+++ b/patches/selftests-vm-only-run-128tbswitch-with-5-level-paging.patch
@@ -1,5 +1,5 @@
 From: Adam Sindelar <adam@wowsignal.io>
-Subject: selftests/vm: Only run 128TBswitch with 5-level paging
+Subject: selftests/vm: only run 128TBswitch with 5-level paging
 Date: Mon, 27 Jun 2022 18:39:12 +0200
 
 The test va_128TBswitch.c expects to be able to pass mmap an address hint
@@ -21,6 +21,10 @@ running ./va_128TBswitch.sh
 [SKIP]
 -------------------------------
 
+[adam@wowsignal.io: restrict the check to x86_64]
+  Link: https://lkml.kernel.org/r/20220628163654.337600-1-adam@wowsignal.io
+[adam@wowsignal.io: fix formatting issues, rename "die" to "fail"]
+  Link: https://lkml.kernel.org/r/20220701163030.415735-1-adam@wowsignal.io
 Link: https://lkml.kernel.org/r/20220627163912.5581-1-adam@wowsignal.io
 Signed-off-by: Adam Sindelar <adam@wowsignal.io>
 Cc: Adam Sindelar <ats@fb.com>
@@ -31,8 +35,8 @@ Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
 
  tools/testing/selftests/vm/Makefile          |    1 
  tools/testing/selftests/vm/run_vmtests.sh    |    2 
- tools/testing/selftests/vm/va_128TBswitch.sh |   39 +++++++++++++++++
- 3 files changed, 41 insertions(+), 1 deletion(-)
+ tools/testing/selftests/vm/va_128TBswitch.sh |   54 +++++++++++++++++
+ 3 files changed, 56 insertions(+), 1 deletion(-)
 
 --- a/tools/testing/selftests/vm/Makefile~selftests-vm-only-run-128tbswitch-with-5-level-paging
 +++ a/tools/testing/selftests/vm/Makefile
@@ -46,7 +50,7 @@ Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
  include ../lib.mk
 --- a/tools/testing/selftests/vm/run_vmtests.sh~selftests-vm-only-run-128tbswitch-with-5-level-paging
 +++ a/tools/testing/selftests/vm/run_vmtests.sh
-@@ -158,7 +158,7 @@ if [ $VADDR64 -ne 0 ]; then
+@@ -151,7 +151,7 @@ if [ $VADDR64 -ne 0 ]; then
  	run_test ./virtual_address_range
  
  	# virtual address 128TB switch test
@@ -57,7 +61,7 @@ Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
  # vmalloc stability smoke test
 --- /dev/null
 +++ a/tools/testing/selftests/vm/va_128TBswitch.sh
-@@ -0,0 +1,39 @@
+@@ -0,0 +1,54 @@
 +#!/bin/bash
 +# SPDX-License-Identifier: GPL-2.0
 +#
@@ -73,26 +77,41 @@ Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
 +# Kselftest framework requirement - SKIP code is 4.
 +ksft_skip=4
 +
-+die()
++fail()
 +{
-+    echo "$1"
-+    exit $exitcode
++	echo "$1"
++	exit $exitcode
++}
++
++check_supported_x86_64()
++{
++	local config="/proc/config.gz"
++	[[ -f "${config}" ]] || config="/boot/config-$(uname -r)"
++	[[ -f "${config}" ]] || fail "Cannot find kernel config in /proc or /boot"
++
++	# gzip -dcfq automatically handles both compressed and plaintext input.
++	# See man 1 gzip under '-f'.
++	local pg_table_levels=$(gzip -dcfq "${config}" | grep PGTABLE_LEVELS | cut -d'=' -f 2)
++
++	if [[ "${pg_table_levels}" -lt 5 ]]; then
++		echo "$0: PGTABLE_LEVELS=${pg_table_levels}, must be >= 5 to run this test"
++		exit $ksft_skip
++	fi
 +}
 +
 +check_test_requirements()
 +{
-+    local config="/proc/config.gz"
-+    [[ -f "${config}" ]] || config="/boot/config-$(uname -r)"
-+    [[ -f "${config}" ]] || die "Cannot find kernel config in /proc or /boot"
-+
-+    # gzip -dcfq automatically handles both compressed and plaintext input.
-+    # See man 1 gzip under '-f'.
-+    local pg_table_levels=$(gzip -dcfq "${config}" | grep PGTABLE_LEVELS | cut -d'=' -f 2)
-+
-+    if [[ "${pg_table_levels}" -lt 5 ]]; then
-+        echo "$0: PG_TABLE_LEVELS=${pg_table_levels}, must be >= 5 to run this test"
-+        exit $ksft_skip
-+    fi
++	# The test supports x86_64 and powerpc64. We currently have no useful
++	# eligibility check for powerpc64, and the test itself will reject other
++	# architectures.
++	case `uname -m` in
++		"x86_64")
++			check_supported_x86_64
++		;;
++		*)
++			return 0
++		;;
++	esac
 +}
 +
 +check_test_requirements
